# -*- coding: utf-8 -*-
"""4101421142_Muhammad Khoirul A'mal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VhEVlmuomLbiBohW8-ZqyL_96sSNGzJL
"""

# Muhammad Khoirul A'mal 4101421142

#Memuat data
import pandas as pd

# Membaca dataset yang diupload
df = pd.read_csv('movie_sample_dataset.csv')

# Menampilkan beberapa baris pertama dari dataset
df.head()

import numpy as np
# Mengganti ? dengan NaN
df.replace("?", np.nan, inplace=True)

# Memeriksa jumlah missing value pada setiap kolom
print (df.isnull().sum())

# Mengecek tipe data
df.dtypes

# Menghapus baris yang memiliki missing value di kolom color, director_name, gross, genres, dan budget
CleanUp = df.dropna(subset=['color','director_name','gross','genres','budget'])

#str.capitalize() digunakan untuk mengubah huruf pertama menjadi kapital agar konsisten
CleanUp['color']=CleanUp['color'].str.capitalize()
CleanUp['actors']=CleanUp['actors'].str.capitalize()

# Menghitung rata-rata gross dan budget kemudian mengisi sel kosong dengan rata-rata
ColsToReplace = ['gross','budget']
for col in ColsToReplace:
  avg_value=df[col].astype(float).mean()
  df[col].replace(np.nan, avg_value, inplace=True)
  print(f"Rata-rata dari gross {col}:{avg_value}")

# Mencari mouds pada kolom director_name, color, genres
modusdirector=df["director_name"].value_counts().idxmax()
moduscolor=df["color"].value_counts().idxmax()
modusgenres=df["genres"].value_counts().idxmax()
# Mengisi sel kosong dengan nilai modus
df["director_name"].replace(np.nan, modusdirector, inplace=True)
df["color"].replace(np.nan, moduscolor, inplace=True)
df["genres"].replace(np.nan, modusgenres, inplace=True)
# Mengecek modus director_name, color, dan genres
print(f"Modus di kolom director_name={modusdirector}")
print(f"Modus di kolom color={moduscolor}")
print(f"Modus di kolom genres={modusgenres}")

# Membuat CleanUp sebagai salinan dari DataFrame asli (df)
CleanUp= df.copy()

# Menghapus baris yang memiliki NaN di kolom gross dan budget
CleanUp = CleanUp.dropna(subset=['gross', 'budget'])

# Memfilter baris dengan nilai budget dan gross yang bernilai negatif
CleanUp = CleanUp[(CleanUp['gross']>=0)&(CleanUp['budget']>=0)]

print(df.isnull().sum())

# Mengubah tipe data kolom yang diperlukan
df[["color", "director_name", "genres"]]=df[["color", "director_name", "genres"]].astype(str)
df[["budget", "gross"]]=df[["budget", "gross"]].astype(float)

# Normalisasi teks ke huruf kecil
CleanUp['color']=CleanUp['color'].str.lower()
CleanUp['director_name']=CleanUp['director_name'].str.lower()
CleanUp['genres']=CleanUp['genres'].str.lower()
CleanUp['language']=CleanUp['language'].str.lower()
CleanUp['country']=CleanUp['country'].str.lower()
CleanUp['actors']=CleanUp['actors'].str.lower()

# Mengecek data-data apakah sudah menjadi huruf kecil semua
print(CleanUp['actors'].head())

# Menyimpan data yang telah diproses ke dalam file CSV baru
CleanUp.to_csv('movie_dataset_cleaned.csv',index=False)